# .github/workflows/schedule-smoke.yml
name: Schedule Smoke Test

on:
  schedule:
    - cron: '*/5 * * * *'  # every 15 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from schedule at $(date -u)"
